### ISSUE TITLE
Failed to build iOS app

### ISSUE THREAD

**Issue by leonardosetiadi** [ochamodev/simple_rsa3#2]
Hi, I got some error while running the app to iOS device

one of the error looks like this:
/.pub-cache/hosted/pub.dartlang.org/simple_rsa3-2.0.1/ios/Classes/SwiftSimpleRsa3Plugin.swift:67:96: error: cannot infer contextual base in reference to member 'sha1'
          let isSuccessful = try! clear.verify(with: publicKey, signature: signature, digestType: .sha1)

Swift Compiler Error (Xcode): Cannot find 'PublicKey' in scope
/.pub-cache/hosted/pub.dartlang.org/simple_rsa3-2.0.1/ios/Classes/SwiftSimpleRsa3Plugin.swift:41:27

It happens only in iOS device, the plugin works great on android. Did I miss something?

**Comment by ochamodev** [comment]
Might have to take a look at what happened there, Right now I don't have a mac to test this. Gonna try to find one, in order to fix it. You can open a PR if you manage to fix this too, I'll be glad to merge it.

**Comment by chamodeveloper** [comment]
@leonardosetiadi I uploaded a new version it's 2.0.2. Should fix the issue. Sorry for the delay.
